/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */





package cv.mikusher.modeloIdentidade.agenda.tela;





/**
 *
 * @author Miky Mikusher Wayne
 */
public class InicioControle extends javax.swing.JFrame {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;





    /**
     * Creates new form Controle
     */
    public InicioControle() {

        initComponents();
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBcalunos = new javax.swing.JButton();
        jBcprofessor = new javax.swing.JButton();
        jBcsair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Controle de Contas");

        jBcalunos.setText("Dados de Alunos");
        jBcalunos.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBcalunosActionPerformed(evt);
            }
        });

        jBcprofessor.setText("Dados de Professor");
        jBcprofessor.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBcprofessorActionPerformed(evt);
            }
        });

        jBcsair.setText("Sair");
        jBcsair.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBcsairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addGroup(jPanel1Layout.createSequentialGroup()
                                                                             .addContainerGap()
                                                                             .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                           .addGap(10, 10, 10)
                                                                                                                           .addComponent(jLabel1))
                                                                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                           .addComponent(jBcprofessor)
                                                                                                                           .addComponent(jBcalunos)
                                                                                                                           .addComponent(jBcsair)))
                                                                             .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { jBcalunos, jBcprofessor, jBcsair });

        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                           .addContainerGap()
                                                                           .addComponent(jLabel1)
                                                                           .addGap(18, 18, 18)
                                                                           .addComponent(jBcalunos)
                                                                           .addGap(18, 18, 18)
                                                                           .addComponent(jBcprofessor)
                                                                           .addGap(18, 18, 18)
                                                                           .addComponent(jBcsair)
                                                                           .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] { jBcalunos, jBcprofessor, jBcsair });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                  layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                      .addGroup(layout.createSequentialGroup()
                                                      .addContainerGap()
                                                      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents





    private void jBcsairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBcsairActionPerformed

        // TODO add your handling code here:
        System.exit(0);
    }// GEN-LAST:event_jBcsairActionPerformed





    private void jBcalunosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBcalunosActionPerformed

        // TODO add your handling code here:
        TelaAlunos tc = new TelaAlunos();
        tc.setLocationRelativeTo(null);
        tc.setVisible(true);
        dispose();
    }// GEN-LAST:event_jBcalunosActionPerformed





    private void jBcprofessorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBcprofessorActionPerformed

        // TODO add your handling code here:
        TelaProfessor tp = new TelaProfessor();
        tp.setLocationRelativeTo(null);
        tp.setVisible(true);
        dispose();
    }// GEN-LAST:event_jBcprofessorActionPerformed





    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioControle.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioControle.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioControle.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioControle.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new InicioControle().setVisible(true);
            }
        });
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcalunos;
    private javax.swing.JButton jBcprofessor;
    private javax.swing.JButton jBcsair;
    private javax.swing.JLabel  jLabel1;
    private javax.swing.JPanel  jPanel1;
    // End of variables declaration//GEN-END:variables
}
