/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */





package cv.mikusher.modeloIdentidade.agenda.tela;





/**
 *
 * @author Miky Mikusher Wayne
 */
public class TelaProfessor extends javax.swing.JFrame {

    /**
     * Creates new form TelaProfessor
     */
    public TelaProfessor() {

        initComponents();
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTidprof = new javax.swing.JTextField();
        jTnomeprof = new javax.swing.JTextField();
        jTtelefoprof = new javax.swing.JTextField();
        jTemailprof = new javax.swing.JTextField();
        jTsexprof = new javax.swing.JTextField();
        jTdepartprof = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTPesQuiProf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProfe = new javax.swing.JTable();
        jBpesqPr = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBAltPro = new javax.swing.JButton();
        jBExcPro = new javax.swing.JButton();
        jBGuaPro = new javax.swing.JButton();
        jBSaiPro = new javax.swing.JButton();
        jBNovPro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Contatos de Professor"));

        jLabel1.setText("Id:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Telefone:");

        jLabel4.setText("Email:");

        jLabel5.setText("Sexo:");

        jLabel6.setText("Departamento:");

        jLabel7.setText("Pesquisa:");

        jTProfe.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { { null, null, null, null }, { null, null, null, null }, { null, null, null, null }, { null, null, null, null } },
                                                                 new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
        jScrollPane1.setViewportView(jTProfe);

        jBpesqPr.setText("Pesquisar");

        jBAltPro.setText("Alterar");

        jBExcPro.setText("Excluir");

        jBGuaPro.setText("Guardar");

        jBSaiPro.setText("Sair");
        jBSaiPro.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBSaiProActionPerformed(evt);
            }
        });

        jBNovPro.setText("Novo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addGroup(jPanel2Layout.createSequentialGroup()
                                                                             .addContainerGap()
                                                                             .addComponent(jBNovPro)
                                                                             .addGap(24, 24, 24)
                                                                             .addComponent(jBAltPro)
                                                                             .addGap(18, 18, 18)
                                                                             .addComponent(jBExcPro)
                                                                             .addGap(18, 18, 18)
                                                                             .addComponent(jBGuaPro)
                                                                             .addGap(18, 18, 18)
                                                                             .addComponent(jBSaiPro)
                                                                             .addContainerGap(81, Short.MAX_VALUE)));

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { jBAltPro, jBExcPro, jBGuaPro, jBNovPro, jBSaiPro });

        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                              jPanel2Layout.createSequentialGroup()
                                                                           .addGap(0, 13, Short.MAX_VALUE)
                                                                           .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                  .addComponent(jBAltPro)
                                                                                                  .addComponent(jBExcPro)
                                                                                                  .addComponent(jBGuaPro)
                                                                                                  .addComponent(jBSaiPro)
                                                                                                  .addComponent(jBNovPro))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addGroup(jPanel1Layout.createSequentialGroup()
                                                                             .addContainerGap()
                                                                             .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                           .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                  .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                                                                         .addComponent(jLabel1)
                                                                                                                                                                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                                         .addComponent(jTidprof,
                                                                                                                                                                                       javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                       67,
                                                                                                                                                                                       javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                  .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                                                                         .addComponent(jLabel2)
                                                                                                                                                                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                                         .addComponent(jTnomeprof,
                                                                                                                                                                                       javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                       168,
                                                                                                                                                                                       javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                  .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                                                                         .addComponent(jLabel5)
                                                                                                                                                                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                                         .addComponent(jTsexprof,
                                                                                                                                                                                       javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                       26,
                                                                                                                                                                                       javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                           .addGap(18, 18, 18)
                                                                                                                           .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                  .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                                                                         .addComponent(jLabel3)
                                                                                                                                                                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                                         .addComponent(jTtelefoprof))
                                                                                                                                                  .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                                                                         .addComponent(jLabel4)
                                                                                                                                                                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                                         .addComponent(jTemailprof))
                                                                                                                                                  .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                                                                         .addComponent(jLabel6)
                                                                                                                                                                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                                         .addComponent(jTdepartprof))))
                                                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                              jPanel1Layout.createSequentialGroup()
                                                                                                                           .addComponent(jLabel7)
                                                                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                           .addComponent(jTPesQuiProf)
                                                                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                           .addComponent(jBpesqPr))
                                                                                                    .addComponent(jScrollPane1)
                                                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                           .addGap(34, 34, 34)
                                                                                                                           .addComponent(jPanel2,
                                                                                                                                         javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                         javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                         Short.MAX_VALUE)))
                                                                             .addContainerGap()));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                           .addGap(18, 18, 18)
                                                                           .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                  .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(jLabel4)
                                                                                                                                                .addComponent(jTemailprof,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                         .addGap(56, 56, 56)
                                                                                                                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(jLabel6)
                                                                                                                                                .addComponent(jTdepartprof,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                  .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(jLabel1)
                                                                                                                                                .addComponent(jTidprof,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                         .addGap(18, 18, 18)
                                                                                                                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(jLabel2)
                                                                                                                                                .addComponent(jTnomeprof,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jLabel3)
                                                                                                                                                .addComponent(jTtelefoprof,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                         .addGap(18, 18, 18)
                                                                                                                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(jLabel5)
                                                                                                                                                .addComponent(jTsexprof,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                           .addGap(18, 18, 18)
                                                                           .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                         .addComponent(jLabel7)
                                                                                                                         .addComponent(jTPesQuiProf,
                                                                                                                                       javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                       javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                       javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                  .addComponent(jBpesqPr))
                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                           .addComponent(jPanel2,
                                                                                         javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                         javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                         javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                           .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                           .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                      .addGroup(layout.createSequentialGroup()
                                                      .addContainerGap()
                                                      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel1.getAccessibleContext()
               .setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents





    private void jBSaiProActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBSaiProActionPerformed

        // TODO add your handling code here:
        System.exit(0);
    }// GEN-LAST:event_jBSaiProActionPerformed





    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new TelaProfessor().setVisible(true);
            }
        });
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton     jBAltPro;
    private javax.swing.JButton     jBExcPro;
    private javax.swing.JButton     jBGuaPro;
    private javax.swing.JButton     jBNovPro;
    private javax.swing.JButton     jBSaiPro;
    private javax.swing.JButton     jBpesqPr;
    private javax.swing.JLabel      jLabel1;
    private javax.swing.JLabel      jLabel2;
    private javax.swing.JLabel      jLabel3;
    private javax.swing.JLabel      jLabel4;
    private javax.swing.JLabel      jLabel5;
    private javax.swing.JLabel      jLabel6;
    private javax.swing.JLabel      jLabel7;
    private javax.swing.JPanel      jPanel1;
    private javax.swing.JPanel      jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField  jTPesQuiProf;
    private javax.swing.JTable      jTProfe;
    private javax.swing.JTextField  jTdepartprof;
    private javax.swing.JTextField  jTemailprof;
    private javax.swing.JTextField  jTidprof;
    private javax.swing.JTextField  jTnomeprof;
    private javax.swing.JTextField  jTsexprof;
    private javax.swing.JTextField  jTtelefoprof;
    // End of variables declaration//GEN-END:variables
}
