/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */





package cv.mikusher.modeloIdentidade.agenda.tela;





import java.sql.SQLException;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import cv.mikusher.modeloIdentidade.agenda.codigo.ContatosAluno;
import cv.mikusher.modeloIdentidade.agenda.combina.ContatoAlunoCombina;





/**
 *
 * @author Miky Mikusher Wayne
 */
public class TelaAlunos extends javax.swing.JFrame {

    DefaultTableModel   tmContato = new DefaultTableModel(null, new String[] { "ID", "Nome", "Endereço", "Telefone", "Email", "Sexo", "Grau", "Disciplinas" });
    List<ContatosAluno> contatos;
    ListSelectionModel  lsmContato;





    /**
     * Creates new form TelaContatos
     */
    public TelaAlunos() {

        initComponents();
        desabilitadata();
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTid = new javax.swing.JTextField();
        jTnome = new javax.swing.JTextField();
        jTtelefone = new javax.swing.JTextField();
        jTendereco = new javax.swing.JTextField();
        jTemail = new javax.swing.JTextField();
        jTsexo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTgrau = new javax.swing.JTextField();
        jTdisciplinas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jBPesquisa = new javax.swing.JButton();
        jTpesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jBNovo = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Do Aluno"));

        jLabel1.setText("Id:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Telefone:");

        jLabel4.setText("Endereço:");

        jLabel5.setText("Email:");

        jLabel6.setText("Sexo:");

        jLabel8.setText("Grau:");

        jLabel9.setText("Nº Disciplinas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addGroup(jPanel1Layout.createSequentialGroup()
                                                                             .addContainerGap()
                                                                             .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                    .addComponent(jLabel3)
                                                                                                    .addComponent(jLabel1)
                                                                                                    .addComponent(jLabel2))
                                                                             .addGap(11, 11, 11)
                                                                             .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                    .addComponent(jTnome)
                                                                                                    .addComponent(jTtelefone,
                                                                                                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                  131,
                                                                                                                  javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                           .addComponent(jTid,
                                                                                                                                         javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                         39,
                                                                                                                                         javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                           .addGap(18, 18, 18)
                                                                                                                           .addComponent(jLabel6)
                                                                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                           .addComponent(jTsexo,
                                                                                                                                         javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                         33,
                                                                                                                                         javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                                                             .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                    .addComponent(jLabel4)
                                                                                                    .addComponent(jLabel5)
                                                                                                    .addComponent(jLabel8))
                                                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                             .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                              jPanel1Layout.createSequentialGroup()
                                                                                                                           .addComponent(jTgrau)
                                                                                                                           .addGap(18, 18, 18)
                                                                                                                           .addComponent(jLabel9)
                                                                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                           .addComponent(jTdisciplinas,
                                                                                                                                         javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                         69,
                                                                                                                                         javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                    .addComponent(jTemail)
                                                                                                    .addComponent(jTendereco,
                                                                                                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                  279,
                                                                                                                  javax.swing.GroupLayout.PREFERRED_SIZE))));

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { jTemail, jTendereco, jTnome, jTtelefone });

        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                           .addContainerGap()
                                                                           .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                  .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(jLabel4)
                                                                                                                                                .addComponent(jTendereco,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                         .addGap(18, 18, 18)
                                                                                                                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(jLabel5)
                                                                                                                                                .addComponent(jTemail,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                         .addGap(38, 38, 38))
                                                                                                  .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                                       .addComponent(jLabel6)
                                                                                                                                                                       .addComponent(jTsexo,
                                                                                                                                                                                     javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                     javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                     javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                                       .addComponent(jLabel1)
                                                                                                                                                                       .addComponent(jTid,
                                                                                                                                                                                     javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                     javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                     javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                         .addGap(18, 18, 18)
                                                                                                                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(jLabel2)
                                                                                                                                                .addComponent(jTnome,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                         .addGap(18, 18, 18)
                                                                                                                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(jLabel3)
                                                                                                                                                .addComponent(jTtelefone,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jLabel8)
                                                                                                                                                .addComponent(jLabel9)
                                                                                                                                                .addComponent(jTgrau,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jTdisciplinas,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                           .addContainerGap(34, Short.MAX_VALUE)));

        jLabel7.setText("Pesquisa:");

        jBPesquisa.setText("Pesquisar");
        jBPesquisa.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBPesquisaActionPerformed(evt);
            }
        });

        jTpesquisar.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jTpesquisarActionPerformed(evt);
            }
        });

        jTable1.setModel(tmContato);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmContato = jTable1.getSelectionModel();
        lsmContato.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {

                if (!e.getValueIsAdjusting()) {
                    tabelaSelecionado(jTable1);
                }
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jBNovo.setText("Novo");
        jBNovo.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBNovoActionPerformed(evt);
            }
        });

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBAlterarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBExcluirActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBGuardarActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addGroup(jPanel2Layout.createSequentialGroup()
                                                                             .addGap(44, 44, 44)
                                                                             .addComponent(jBNovo)
                                                                             .addGap(18, 18, 18)
                                                                             .addComponent(jBAlterar)
                                                                             .addGap(18, 18, 18)
                                                                             .addComponent(jBExcluir)
                                                                             .addGap(18, 18, 18)
                                                                             .addComponent(jBGuardar)
                                                                             .addGap(18, 18, 18)
                                                                             .addComponent(jBSair)
                                                                             .addContainerGap(56, Short.MAX_VALUE)));

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { jBAlterar, jBExcluir, jBGuardar, jBNovo, jBSair });

        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                                           .addContainerGap()
                                                                           .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                  .addComponent(jBNovo)
                                                                                                  .addComponent(jBAlterar)
                                                                                                  .addComponent(jBExcluir)
                                                                                                  .addComponent(jBGuardar)
                                                                                                  .addComponent(jBSair))
                                                                           .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jScrollPane1)
                                                                        .addComponent(jPanel1,
                                                                                      javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                      Short.MAX_VALUE)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                  layout.createSequentialGroup()
                                                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(jLabel7)
                                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                                        .addComponent(jTpesquisar,
                                                                                                                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                      218,
                                                                                                                                      javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                        .addComponent(jBPesquisa)))))
                                                        .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                  layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(127, 127, 127)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                      .addGroup(layout.createSequentialGroup()
                                                      .addGap(12, 12, 12)
                                                      .addComponent(jLabel7)
                                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                      .addComponent(jBPesquisa)
                                                                      .addComponent(jTpesquisar,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE))
                                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                      .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                                      .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents





    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBNovoActionPerformed

        // TODO add your handling code here:
        habilitadata();
        jTnome.setText("");
        jTendereco.setText("");
        jTemail.setText("");
        jTtelefone.setText("");
        jTsexo.setText("");
        jTgrau.setText("");
        jTdisciplinas.setText("");
    }// GEN-LAST:event_jBNovoActionPerformed





    public void listarContato() throws SQLException {

        ContatoAlunoCombina cc = new ContatoAlunoCombina();
        contatos = cc.getLista("%" + jTpesquisar.getText() + "%");
        mostrarPesquisa(contatos);
    }





    public void desabilitadata() {

        jTid.setEditable(false);
        jTnome.setEditable(false);
        jTendereco.setEditable(false);
        jTsexo.setEditable(false);
        jTtelefone.setEditable(false);
        jTemail.setEditable(false);
        jTgrau.setEditable(false);
        jTdisciplinas.setEditable(false);
    }





    public void habilitadata() {

        jTnome.setEditable(true);
        jTendereco.setEditable(true);
        jTsexo.setEditable(true);
        jTtelefone.setEditable(true);
        jTemail.setEditable(true);
        jTgrau.setEditable(true);
        jTdisciplinas.setEditable(true);
    }





    public boolean verificaDados() {

        if (!jTnome.getText()
                   .equals("")
            && !jTgrau.getText()
                      .equals("")) {

            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Campo de Nome ou Grau, a ser preenchidos");
        }
        return false;
    }





    private void tabelaSelecionado(JTable tabela) {

        if (jTable1.getSelectedRow() != -1) {
            habilitadata();
            jTid.setText(String.valueOf(contatos.get(tabela.getSelectedRow())
                                                .getId()));
            jTnome.setText(contatos.get(tabela.getSelectedRow())
                                   .getNome());
            jTendereco.setText(contatos.get(tabela.getSelectedRow())
                                       .getEndereco());
            jTemail.setText(contatos.get(tabela.getSelectedRow())
                                    .getEmail());
            jTtelefone.setText(contatos.get(tabela.getSelectedRow())
                                       .getTelefone());
            jTsexo.setText(contatos.get(tabela.getSelectedRow())
                                   .getSexo());
            jTgrau.setText(contatos.get(tabela.getSelectedRow())
                                   .getGrau());
            jTdisciplinas.setText(contatos.get(tabela.getSelectedRow())
                                          .getDisciplinas());
        } else {
            jTid.setText("");
            jTnome.setText("");
            jTendereco.setText("");
            jTtelefone.setText("");
            jTsexo.setText("");
            jTemail.setText("");
            jTgrau.setText("");
            jTdisciplinas.setText("");
        }
    }





    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBGuardarActionPerformed

        if (verificaDados()) {
            Guarda();
            desabilitadata();
        }
    }// GEN-LAST:event_jBGuardarActionPerformed





    private void jBPesquisaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBPesquisaActionPerformed

        try {
            // TODO add your handling code here:
            listarContato();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problemas na Pesquisa");
        }
    }// GEN-LAST:event_jBPesquisaActionPerformed





    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBExcluirActionPerformed

        try {
            // TODO add your handling code here:
            excluirCont();
            listarContato();
            // mostrarPesquisa(contatos);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro em Excluir!" + ex);
        }
    }// GEN-LAST:event_jBExcluirActionPerformed





    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBAlterarActionPerformed

        try {
            alterarContatos();
            listarContato();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problemas no botão alterar");
        }
    }// GEN-LAST:event_jBAlterarActionPerformed





    private void jTpesquisarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTpesquisarActionPerformed

        // TODO add your handling code here:
    }// GEN-LAST:event_jTpesquisarActionPerformed





    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBSairActionPerformed

        // TODO add your handling code here:
        System.exit(0);
    }// GEN-LAST:event_jBSairActionPerformed





    public void excluirCont() throws SQLException {

        int dica = JOptionPane.showConfirmDialog(this, "Deseja Apagar o Contato?", "Confirma!", JOptionPane.YES_NO_OPTION);
        if (dica == JOptionPane.YES_NO_OPTION) {
            ContatoAlunoCombina cc = new ContatoAlunoCombina();
            cc.remove(contatos.get(jTable1.getSelectedRow()));
        }
    }





    public void Guarda() {

        try {
            // TODO add your handling code here:
            ContatosAluno ct = new ContatosAluno();
            ct.setNome(jTnome.getText());
            ct.setEndereco(jTendereco.getText());
            ct.setEmail(jTemail.getText());
            ct.setTelefone(jTtelefone.getText());
            ct.setSexo(jTsexo.getText());
            ct.setGrau(jTgrau.getText());
            ct.setDisciplinas(jTdisciplinas.getText());

            ContatoAlunoCombina dao = new ContatoAlunoCombina();
            dao.adiciona(ct);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problemas em Pesquisa");
        }
    }





    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlunos.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlunos.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlunos.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlunos.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                TelaAlunos tcc = new TelaAlunos();
                tcc.setLocationRelativeTo(null);
                tcc.setVisible(true);
            }
        });
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton     jBAlterar;
    private javax.swing.JButton     jBExcluir;
    private javax.swing.JButton     jBGuardar;
    private javax.swing.JButton     jBNovo;
    private javax.swing.JButton     jBPesquisa;
    private javax.swing.JButton     jBSair;
    private javax.swing.JLabel      jLabel1;
    private javax.swing.JLabel      jLabel2;
    private javax.swing.JLabel      jLabel3;
    private javax.swing.JLabel      jLabel4;
    private javax.swing.JLabel      jLabel5;
    private javax.swing.JLabel      jLabel6;
    private javax.swing.JLabel      jLabel7;
    private javax.swing.JLabel      jLabel8;
    private javax.swing.JLabel      jLabel9;
    private javax.swing.JPanel      jPanel1;
    private javax.swing.JPanel      jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable      jTable1;
    private javax.swing.JTextField  jTdisciplinas;
    private javax.swing.JTextField  jTemail;
    private javax.swing.JTextField  jTendereco;
    private javax.swing.JTextField  jTgrau;
    private javax.swing.JTextField  jTid;
    private javax.swing.JTextField  jTnome;
    private javax.swing.JTextField  jTpesquisar;
    private javax.swing.JTextField  jTsexo;
    private javax.swing.JTextField  jTtelefone;
    // End of variables declaration//GEN-END:variables





    private void mostrarPesquisa(List<ContatosAluno> contatos) {

        while (tmContato.getRowCount() > 0) {
            tmContato.removeRow(0);
        }
        if (contatos.size() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhum contato cadastrado");
        } else {
            String[] linha = new String[] { null, null, null, null, null, null, null, null };
            for (int i = 0; i < contatos.size(); i++) {
                tmContato.addRow(linha);
                tmContato.setValueAt(contatos.get(i)
                                             .getId(),
                                     i,
                                     0);
                tmContato.setValueAt(contatos.get(i)
                                             .getNome(),
                                     i,
                                     1);
                tmContato.setValueAt(contatos.get(i)
                                             .getEndereco(),
                                     i,
                                     2);
                tmContato.setValueAt(contatos.get(i)
                                             .getEmail(),
                                     i,
                                     4);
                tmContato.setValueAt(contatos.get(i)
                                             .getTelefone(),
                                     i,
                                     3);
                tmContato.setValueAt(contatos.get(i)
                                             .getSexo(),
                                     i,
                                     5);
                tmContato.setValueAt(contatos.get(i)
                                             .getGrau(),
                                     i,
                                     6);
                tmContato.setValueAt(contatos.get(i)
                                             .getDisciplinas(),
                                     i,
                                     7);
            }

        }
    }





    private void alterarContatos() throws SQLException {

        if (jTable1.getSelectedRow() != -1) {
            if (verificaDados()) {
                ContatosAluno c1 = new ContatosAluno();
                ContatoAlunoCombina cc = new ContatoAlunoCombina();
                c1.setId(Long.valueOf(jTid.getText()));
                c1.setNome(jTnome.getText());
                c1.setEndereco(jTendereco.getText());
                c1.setTelefone(jTtelefone.getText());
                c1.setEmail(jTemail.getText());
                c1.setSexo(jTsexo.getText());
                c1.setGrau(jTgrau.getText());
                c1.setDisciplinas(jTdisciplinas.getText());
                cc.altera(c1);
                JOptionPane.showMessageDialog(null, "Alteração, com sucesso!");
            }
        }
    }
}
