/*
 * Copyright (C) 2016 Miky Mikusher Wayne
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 */
package cv.mikusher.banco.ferramenta;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.WindowEvent;

/**
 *
 * @author Miky Mikusher Wayne
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        visorescrita = new javax.swing.JTextField();
        sair = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        sinalsoma = new javax.swing.JButton();
        nun1 = new javax.swing.JButton();
        nun2 = new javax.swing.JButton();
        nun3 = new javax.swing.JButton();
        nun4 = new javax.swing.JButton();
        nun5 = new javax.swing.JButton();
        nun6 = new javax.swing.JButton();
        nun7 = new javax.swing.JButton();
        nun8 = new javax.swing.JButton();
        nun9 = new javax.swing.JButton();
        sinalsubtrair = new javax.swing.JButton();
        sinaldivisor = new javax.swing.JButton();
        sinalmultiplica = new javax.swing.JButton();
        sinaligual = new javax.swing.JButton();
        nun0 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        visorescrita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visorescritaActionPerformed(evt);
            }
        });

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        sinalsoma.setText("+");
        sinalsoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinalsomaActionPerformed(evt);
            }
        });

        nun1.setText("1");
        nun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nun1ActionPerformed(evt);
            }
        });

        nun2.setText("2");
        nun2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nun2ActionPerformed(evt);
            }
        });

        nun3.setText("3");
        nun3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nun3ActionPerformed(evt);
            }
        });

        nun4.setText("4");
        nun4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nun4ActionPerformed(evt);
            }
        });

        nun5.setText("5");
        nun5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nun5ActionPerformed(evt);
            }
        });

        nun6.setText("6");
        nun6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nun6ActionPerformed(evt);
            }
        });

        nun7.setText("7");
        nun7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nun7ActionPerformed(evt);
            }
        });

        nun8.setText("8");
        nun8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nun8ActionPerformed(evt);
            }
        });

        nun9.setText("9");
        nun9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nun9ActionPerformed(evt);
            }
        });

        sinalsubtrair.setText("-");
        sinalsubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinalsubtrairActionPerformed(evt);
            }
        });

        sinaldivisor.setText("/");
        sinaldivisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinaldivisorActionPerformed(evt);
            }
        });

        sinalmultiplica.setText("*");
        sinalmultiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinalmultiplicaActionPerformed(evt);
            }
        });

        sinaligual.setText("=");
        sinaligual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinaligualActionPerformed(evt);
            }
        });

        nun0.setText("0");
        nun0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nun0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visorescrita)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nun7, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nun0, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(nun8)
                                            .addGap(18, 18, 18)
                                            .addComponent(nun9))
                                        .addComponent(sinaligual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(nun4)
                                    .addGap(18, 18, 18)
                                    .addComponent(nun5)
                                    .addGap(18, 18, 18)
                                    .addComponent(nun6))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(nun1)
                                    .addGap(18, 18, 18)
                                    .addComponent(nun2)
                                    .addGap(18, 18, 18)
                                    .addComponent(nun3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sinalsoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sinalsubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sinalmultiplica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sinaldivisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(sair, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(visorescrita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sair)
                    .addComponent(limpar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nun1)
                    .addComponent(nun2)
                    .addComponent(nun3))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nun6)
                    .addComponent(nun5)
                    .addComponent(nun4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nun9)
                    .addComponent(nun8)
                    .addComponent(nun7)
                    .addComponent(sinalmultiplica)
                    .addComponent(sinalsoma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nun0)
                    .addComponent(sinaligual)
                    .addComponent(sinalsubtrair)
                    .addComponent(sinaldivisor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Calculadora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private float valor = 0;
    private int operacao = 0;
    
    public void setValor()
    {
        this.valor = Float.parseFloat(visorescrita.getText());
    }
    
    public float getValor() 
    {
        return valor;
    }
    
    public void windowOpened(WindowEvent evt)
    {
        visorescrita.requestFocus();
    }
    private void sinalsomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinalsomaActionPerformed
        // TODO add your handling code here:
        setValor();
        operacao = 1;
    }//GEN-LAST:event_sinalsomaActionPerformed

    private void nun0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nun0ActionPerformed
        // TODO add your handling code here:
        visorescrita.setText("0");
    }//GEN-LAST:event_nun0ActionPerformed

    private void nun8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nun8ActionPerformed
        // TODO add your handling code here:
        visorescrita.setText("8");
    }//GEN-LAST:event_nun8ActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:
        valor = 0;
        visorescrita.setText("");
    }//GEN-LAST:event_limparActionPerformed

    private void visorescritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visorescritaActionPerformed
        // TODO add your handling code here:
        visorescrita.setEditable(false);
        visorescrita.setBackground(Color.YELLOW);
        visorescrita.setHorizontalAlignment(WIDTH);
        add(visorescrita, BorderLayout.NORTH);
    }//GEN-LAST:event_visorescritaActionPerformed

    private void nun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nun1ActionPerformed
        // TODO add your handling code here:
        visorescrita.setText("1");
    }//GEN-LAST:event_nun1ActionPerformed

    private void nun2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nun2ActionPerformed
        // TODO add your handling code here:
        visorescrita.setText("2");
    }//GEN-LAST:event_nun2ActionPerformed

    private void nun3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nun3ActionPerformed
        // TODO add your handling code here:
        visorescrita.setText("3");
    }//GEN-LAST:event_nun3ActionPerformed

    private void nun4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nun4ActionPerformed
        // TODO add your handling code here:
        visorescrita.setText("4");
    }//GEN-LAST:event_nun4ActionPerformed

    private void nun5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nun5ActionPerformed
        // TODO add your handling code here:
        visorescrita.setText("5");
    }//GEN-LAST:event_nun5ActionPerformed

    private void nun6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nun6ActionPerformed
        // TODO add your handling code here:
        visorescrita.setText("6");
    }//GEN-LAST:event_nun6ActionPerformed

    private void nun7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nun7ActionPerformed
        // TODO add your handling code here:
        visorescrita.setText("7");
    }//GEN-LAST:event_nun7ActionPerformed

    private void nun9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nun9ActionPerformed
        // TODO add your handling code here:
        visorescrita.setText("9");
    }//GEN-LAST:event_nun9ActionPerformed

    private void sinalmultiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinalmultiplicaActionPerformed
        // TODO add your handling code here:
        setValor();
        operacao = 4;
    }//GEN-LAST:event_sinalmultiplicaActionPerformed

    private void sinalsubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinalsubtrairActionPerformed
        // TODO add your handling code here:
        setValor();
        operacao = 2;
    }//GEN-LAST:event_sinalsubtrairActionPerformed

    private void sinaldivisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinaldivisorActionPerformed
        // TODO add your handling code here:
        setValor();
        operacao = 3;
    }//GEN-LAST:event_sinaldivisorActionPerformed

    private void sinaligualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinaligualActionPerformed
        // TODO add your handling code here:
        switch (operacao)
        {
            //somar 
            case 1:
            {
                operacao = 0;
                visorescrita.setText(Float.toString(getValor() + Float.parseFloat(visorescrita.getText())));
                break;
            }
            
            //subtrair 
            case 2:
            {
                operacao = 0;
                visorescrita.setText(Float.toString(getValor() - Float.parseFloat(visorescrita.getText())));
                break;
            }
            
            //dividir 
            case 3:
            {
                try
                {
                operacao = 0;
                visorescrita.setText(Float.toString(getValor() / Float.parseFloat(visorescrita.getText())));
                }
                catch(ArithmeticException ex)
                {
                    visorescrita.setText("");
                    System.out.println("Não se pode dividir por zero! Erro:" + ex.getMessage());
                }
                break;
            }
            
            //multiplicar
            case 4:
            {
                operacao = 0;
                visorescrita.setText(Float.toString(getValor() * Float.parseFloat(visorescrita.getText())));
                break;
            }
            default:
                System.out.println("Inicia a Operação");
                break;
        }
        
    }//GEN-LAST:event_sinaligualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpar;
    private javax.swing.JButton nun0;
    private javax.swing.JButton nun1;
    private javax.swing.JButton nun2;
    private javax.swing.JButton nun3;
    private javax.swing.JButton nun4;
    private javax.swing.JButton nun5;
    private javax.swing.JButton nun6;
    private javax.swing.JButton nun7;
    private javax.swing.JButton nun8;
    private javax.swing.JButton nun9;
    private javax.swing.JButton sair;
    private javax.swing.JButton sinaldivisor;
    private javax.swing.JButton sinaligual;
    private javax.swing.JButton sinalmultiplica;
    private javax.swing.JButton sinalsoma;
    private javax.swing.JButton sinalsubtrair;
    private javax.swing.JTextField visorescrita;
    // End of variables declaration//GEN-END:variables
}
