/*
 * Copyright (C) 2017 Miky Mikusher
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */
/**
 * Luis Amilcar Tavares
 */





package cv.mikusher.agenda.classe;





import static cv.mikusher.agenda.classe.LoggOperation.LOGGER;

import java.awt.HeadlessException;
import java.util.logging.Level;

import javax.swing.JOptionPane;

import cv.mikusher.agenda.classe.sqlClass.ConnectionToSQL;





/**
 *
 * @author Miky Mikusher
 */
public class Login extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Login
     */
    ConnectionToSQL           ctdb             = new ConnectionToSQL();





    public Login() {

        initComponents();
        this.setLocationRelativeTo(null);
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtUsername = new javax.swing.JTextField();
        jtPassword = new javax.swing.JPasswordField();
        jbLogin = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jLabel2.setText("LOGIN");

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        jbLogin.setText("Login");
        jbLogin.addActionListener(new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbLoginActionPerformed(evt);
            }
        });

        jbCancel.setText("Cancel");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                  layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                  layout.createSequentialGroup()
                                                                                        .addComponent(jLabel4)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(jtPassword))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                        .addGap(0, 63, Short.MAX_VALUE)
                                                                                        .addComponent(jbLogin)
                                                                                        .addGap(18, 18, 18)
                                                                                        .addComponent(jbCancel))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(jLabel3)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(jtUsername)))
                                                        .addGap(30, 30, 30)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                      .addGroup(layout.createSequentialGroup()
                                                      .addContainerGap()
                                                      .addComponent(jLabel2)
                                                      .addGap(30, 30, 30)
                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                      .addComponent(jtPassword,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                      .addGroup(layout.createSequentialGroup()
                                                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                      .addComponent(jLabel3)
                                                                                                      .addComponent(jtUsername,
                                                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                      .addGap(18, 18, 18)
                                                                                      .addComponent(jLabel4)))
                                                      .addGap(18, 18, 18)
                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                      .addComponent(jbLogin)
                                                                      .addComponent(jbCancel))
                                                      .addContainerGap(17, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents





    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbCancelActionPerformed

        // TODO add your handling code here:
        System.exit(0);
    }// GEN-LAST:event_jbCancelActionPerformed





    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbLoginActionPerformed

        // TODO add your handling code here:
        try {
            if (ConnectionToSQL.loginCheck(this.jtUsername.getText(), String.valueOf(this.jtPassword.getPassword()))) {
                new Gui().setVisible(true);
                this.dispose();
                this.setResizable(false);

            } else {
                JOptionPane.showMessageDialog(null, "Dados errado. Tente novamente!");
                this.jtUsername.setText("");
                this.jtPassword.setText("");
            }
        } catch (HeadlessException e) {
            // TODO Auto-generated catch block
            LOGGER.log(Level.SEVERE, "Não é possivel adicionar utilizador.", e);
        }
    }// GEN-LAST:event_jbLoginActionPerformed





    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {

                new Login().setVisible(true);
            }
        });
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel         jLabel1;
    private javax.swing.JLabel         jLabel2;
    private javax.swing.JLabel         jLabel3;
    private javax.swing.JLabel         jLabel4;
    private javax.swing.JButton        jbCancel;
    private javax.swing.JButton        jbLogin;
    private javax.swing.JPasswordField jtPassword;
    private javax.swing.JTextField     jtUsername;
    // End of variables declaration//GEN-END:variables
}
