/*
 * Copyright (C) 2016 Miky Mikusher Wayne
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 */
package cv.mikusher.qsllite.principal;

import cv.mikusher.qsllite.Sql2_CreateDataBase;
import cv.mikusher.qsllite.Sql3_CreateTable;
import javax.swing.JOptionPane;

/**
 *
 * @author Miky Mikusher Wayne
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtDataBaseName = new javax.swing.JTextField();
        jBCreateDataBase = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtDataBaseNameCTable = new javax.swing.JTextField();
        jBCreateTable = new javax.swing.JButton();
        jtTableName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtExtension = new javax.swing.JTextField();
        ext = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jtDiretory = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SQLlite");

        jLabel1.setText("DATA BASE - SqlLite");

        jLabel2.setText("Create Data Base:");

        jBCreateDataBase.setText("Create");
        jBCreateDataBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCreateDataBaseActionPerformed(evt);
            }
        });

        jLabel3.setText("Create Table:");

        jBCreateTable.setText("Create");
        jBCreateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCreateTableActionPerformed(evt);
            }
        });

        jLabel4.setText("Data Base Name");

        jLabel5.setText("Data Base Name");

        jLabel6.setText("Table Name");

        ext.setText("Extensão");

        jLabel7.setText("Diretory (eg: D:/SqlLiteData/)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(301, 301, 301))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtDiretory, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jtDataBaseNameCTable, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ext))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtTableName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15)
                                    .addComponent(jBCreateTable))))
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jtDataBaseName, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jBCreateDataBase))
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(3, 3, 3)
                .addComponent(jtDiretory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jtDataBaseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBCreateDataBase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(ext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCreateTable)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtDataBaseNameCTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtExtension)
                                .addComponent(jtTableName)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCreateDataBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCreateDataBaseActionPerformed
        // TODO add your handling code here:
        Sql2_CreateDataBase cd = new Sql2_CreateDataBase();
        String cdDataBase = (String)jtDataBaseName.getText();
        String cdDirectory = (String)jtDiretory.getText();
        jtExtension.setEditable(false);
        
        if (jtDataBaseName.getText().equals("") || jtDiretory.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo não pode estar limpo");
        } else {
            Sql2_CreateDataBase.createNewDatabase(cdDirectory, cdDataBase+".s3db");
            JOptionPane.showMessageDialog(null, "Base de dados "+cdDataBase+" criado com sucesso!");
            jtDataBaseName.setText("");
            jtDataBaseNameCTable.setText("");
            jtDataBaseNameCTable.setText(cdDataBase);
            jtExtension.setText(".s3db");
        } 
    }//GEN-LAST:event_jBCreateDataBaseActionPerformed

    private void jBCreateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCreateTableActionPerformed
        // TODO add your handling code here:
        Sql3_CreateTable cd = new Sql3_CreateTable();
        String cdTable = (String)jtDataBaseNameCTable.getText();
        String cdName = (String)jtTableName.getText();
        String cdDirectory = (String)jtDiretory.getText();
        
        if (jtDataBaseNameCTable.getText().equals("") || jtTableName.getText().equals("") || jtDiretory.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo não pode estar limpo");
            
        } else if (jtExtension.getText().equals("") || !jtExtension.getText().equals(".s3db")){
            jtExtension.setText(".s3db");
            Sql3_CreateTable.createNewTable(cdDirectory, cdTable+".s3db", cdName);
            JOptionPane.showMessageDialog(null, "Na base de dados "+cdTable+" foi criado a tabela "+cdName+" com sucesso, e extensão mudada para .s3db");
            jtDataBaseNameCTable.setText("");
            jtExtension.setText("");
            jtTableName.setText("");
            
        } else {
            Sql3_CreateTable.createNewTable(cdDirectory, cdTable+".s3db", cdName);
            JOptionPane.showMessageDialog(null, "Na base de dados "+cdTable+" foi criado a tabela "+cdName+" com sucesso!");
            jtDataBaseNameCTable.setText("");
            jtExtension.setText("");
            jtTableName.setText("");
        }
    }//GEN-LAST:event_jBCreateTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ext;
    private javax.swing.JButton jBCreateDataBase;
    private javax.swing.JButton jBCreateTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jtDataBaseName;
    private javax.swing.JTextField jtDataBaseNameCTable;
    private javax.swing.JTextField jtDiretory;
    private javax.swing.JTextField jtExtension;
    private javax.swing.JTextField jtTableName;
    // End of variables declaration//GEN-END:variables
}